#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
/usr/local/lsf/etc/job_starter 'source /afs/cern.ch/work/s/sigamani/public/CMSSW_5_3_14_STOPS/src/Stops-AN-14-067/runExtender/batch_output/ttbar_madgraph_1l/src/ttbar_madgraph_1l.src'
ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
